#!/bin/bash
# brightctl
# adds or subtrackts from the brightness setting

# Copyright (C) 2014-2015 Alexander Swen <alex@swen.nu>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Alexander Swen
# Private contact: alex@swen.nu

# CHANGELOG:
# 20140520	A.Swen	  created.
# 20199220      R.Postill Refined to be not specific to host or device type.
# 20190220      R.Postill Added step caculation based on the first device also to be %1 per up/down.
# 20190220      R.Postill Remove unused variables.

# SETTINGS
me=$(basename $0)

# FUNCTIONS
die () {
  rc=$1
  shift
  echo "==========================">&2
  echo "====    FATAL  ERROR  ====" >&2
  echo "==========================">&2
  echo "" >&2
  echo $@ >&2
  exit $rc
}

usage () {
  echo "==========================" >&2
  echo "====       USAGE      ====" >&2
  echo "==========================" >&2
  echo "" >&2
  echo "Usage: ${me} <up> or <down> [device]" >&2
  echo "" >&2
  echo "example: ${me} up" >&2
  echo "example: ${me} up intel_backlight" >&2
  echo "" >&2
  exit 1
}

# SCRIPT
[ ${UID} -gt 0 ] && die 1 only root may do that

if [ ! -z $2 ]; then
  device="$2"
else
  device="*"
fi

ctlfile="/sys/class/backlight/$device/brightness"

[ -f ${ctlfile} ] || die 2 controlfile ${ctlfile} not found

max_brightness=$(cat /sys/class/backlight/$device/max_brightness | head -n1)
step=$(expr $max_brightness / 100)
br=$(cat ${ctlfile})

case $1 in
  up) newbr=$((br+step));;
down) newbr=$((br-step));;
  *) usage;;
esac
echo ${newbr} > ${ctlfile}

# END
