#!/usr/bin/env bash

source /home/rpostill/.config/secrets/screenshot
FORMAT=$(date '+%Y-%M-%H_%S_%V%N%U%s')
DIRECTORY="/home/rpostill/Pictures/screenshots"
FINAL="/srv/www/ss/"
SCROT="/usr/bin/scrot"
SCREENSHOT="$DIRECTORY/$FORMAT.png"
REMOTESHOT="$FINAL/$FORMAT.png"

$SCROT -s "$SCREENSHOT"
scp $SCREENSHOT $USER@$HOST:$REMOTESHOT
echo "http://$HOST/ss/$FORMAT.png" | xclip -sel clip
/usr/bin/google-chrome "http://$HOST/ss/$FORMAT.png"
