#!/usr/bin/env bash

# HOST, USER, FORMAT in secrets
source ~/.config/secrets/screenshot

DIRECTORY="$HOME/Pictures/screenshots"
FINAL="/srv/www/ss/"
SCROT="/usr/bin/scrot"
SCREENSHOT="$DIRECTORY/$FORMAT.png"
REMOTESHOT="$FINAL/$FORMAT.png"

$SCROT -s "$SCREENSHOT"
scp $SCREENSHOT $USER@$HOST:$REMOTESHOT
retval=$?
if [ $retval -eq 0 ]; then
  echo "http://$HOST/ss/$FORMAT.png" | xclip -sel clip
  notify-send "Screenshot" "Link copied"
  /usr/bin/google-chrome "http://$HOST/ss/$FORMAT.png"
else
  notify-send "Screenshot" "Failed exit code: $?"
fi

