#!/usr/bin/env bash

# HOST, USER, FORMAT in secrets
source ~/.config/secrets/screenshot

DIRECTORY="~/Pictures/screenshots"
FINAL="/srv/www/ss/"
SCROT="/usr/bin/scrot"
SCREENSHOT="$DIRECTORY/$FORMAT.png"
REMOTESHOT="$FINAL/$FORMAT.png"

$SCROT -s "$SCREENSHOT"
scp $SCREENSHOT $USER@$HOST:$REMOTESHOT
echo "http://$HOST/ss/$FORMAT.png" | xclip -sel clip
/usr/bin/google-chrome "http://$HOST/ss/$FORMAT.png"
